In [26]:
import tensorflow
from tensorflow.keras.models import load_model 
import pickle
import numpy as np
import pandas as pd

In [27]:
### load the trained model ,scaler pickle ,OHE

model = load_model('model.h5')


## load the encoder and scaler 

with open('onehot_encoder_geo.pkl','rb') as file :
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file :
    label_encoder_gender=pickle.load(file)

with open('scaler.pkl','rb') as file :
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [28]:
input_data ={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts': 2 ,
    'HasCrCard':1 ,
    'IsActiveMember':1,
    'EstimatedSalary':50000
    }

In [29]:
### One hot encode 'Geography'

geo_encode = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encode_df = pd.DataFrame(geo_encode,columns= label_encoder_geo.get_feature_names_out(['Geography']))
geo_encode_df

c:\CLASSRO0M\envs\annenv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [30]:
geo_encode = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encode_df = pd.DataFrame(geo_encode, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encode_df

c:\CLASSRO0M\envs\annenv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [31]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [32]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [33]:
### Concatenation one hot encoded 

input_df= pd.concat([input_df.drop("Geography",axis=1),geo_encode_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [34]:
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.51104873,  0.90134069,  0.09291598, -0.69444113, -0.26649227,
         0.80268517,  0.64104192,  0.97067965, -0.85598661,  1.00125078,
        -0.57715782, -0.57850497]])

In [35]:
### Predict Churn 

prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 453ms/step

array([[0.07073096]], dtype=float32)

In [36]:
prediction_probability = prediction[0][0]
prediction_probability

np.float32(0.07073096)

In [38]:
if prediction_probability > 0.5:
    print(f"Customer WILL churn  (Probability: {prediction_probability:.2%})")
else:
    print(f"Customer will NOT churn  (Probability: {prediction_probability:.2%})")

Customer will NOT churn  (Probability: 7.07%)